### ISSUE TITLE
Cannot find fakenet

### ISSUE THREAD

**Issue by antman1p** [mandiant/flare-vm#212]
After running the flarevm ps1 installation script, fakenet is nowhere to be found.  I tried insatllaing it with pip and after install it gives a syntax error.

**Comment by MalwareMechanic** [comment]
@antman1p Can you try running the following command and let me know if it installs fakenet: `py -2 -m pip install https://github.com/fireeye/flare-fakenet-ng/archive/master.zip`

**Comment by antman1p** [comment]
I was able to do it from here: pip install https://github.com/fireeye/flare-fakenet-ng/zipball/master
However, It appears that the flareVM uses python3 and this fakenet seems to have been written in python 2.7.

**Comment by strictlymike** [comment]
Was this syntax error the one that you fixed in <https://github.com/fireeye/flare-fakenet-ng/pull/114>? If it isn't, I'd be curious to know what the syntax error was, if you can produce more details readily.

If that pull request was strictly for Python3 compliance, heads-up, we haven't gone through to make FakeNet-NG compatible with Python3 yet, but I suspect this is just the tip of the iceberg when it comes to making it run under Python3. Not that I expect it to be too onerous, but I do expect a multitude of minor items to arise when we begin that task.

**Comment by MalwareMechanic** [comment]
@antman1p FLARE VM uses Python3 as the default Python version. You'll need to install fakenet using `py -2 -m pip` in order to install it using Python2 as `pip` will default to Python3. Can you confirm it installs correctly using `py -2 -m pip install https://github.com/fireeye/flare-fakenet-ng/archive/master.zip`?

You can also attempt to install it via Chocolatey by opening an admin PowerShell prompt and running: `choco install fakenet-ng.python.flare`

**Comment by MalwareMechanic** [comment]
@antman1p are you still having an issue with fakenet?

**Comment by antman1p** [comment]
My apologies, I had moved on to another project.  I will check on Monday.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
