### ISSUE TITLE
Has FireEye stopped Flare VM project?

### ISSUE THREAD

**Issue by CryptoHackz** [mandiant/flare-vm#359]
For weeks, if not months... I'm unable to install Flare VM is any of the Windows 7 developer VMs? Or even my own licensed fresh install installed win7. Has production... or improvements has been put on hold?

**Comment by htnhan** [comment]
Hi @CryptoHackz,

We still maintain and continue to provide bug fixes and improvements to FLARE-VM. 

If you run into any issues, please create a ticket here so we can provide assistance.

Thank you

**Comment by MalwareMechanic** [comment]
Hey @CryptoHackz,

I'm currently performing a test install on Win7 and it's going smoothly. I'll report if I run into any issues.

Thanks!

**Comment by MalwareMechanic** [comment]
Hey @CryptoHackz,

I performed a fresh install over the weekend. I ran into one error early on, but it seemed related to a process timeout issue when setting registry keys for Win7 in the `flarevm.installer.flare` package. Instead of diving too deep, I ran the `install.ps1` script again and it worked as expected.

A few packages that are known to fail on Win7 due to TLS issues are noted below:
- bytehist.fireeye
- vbdecompiler.flare

The package below is also broken due to a dead link with no alternative links:
- x64dbg.py.flare

Hope this helps!

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
