### ISSUE TITLE
Error with myget.org

### ISSUE THREAD

**Issue by Evan-Sa** [mandiant/flare-vm#390]
Hello,

First time encountering this when updating or installing the latest packages. I tried following the latest instructions but encountered an issue where myget.org was prompting me for credentials. Did something change with calling the myget api to cause the script to break or are we required to sign up for a myget account going forward when we install.  See the attached 

![Capture](https://user-images.githubusercontent.com/10689431/147497387-55445b59-5e60-4158-a92f-32cb344bfb9e.JPG)

**Comment by MalwareMechanic** [comment]
@Evan-Sa Odd, we've since deprecated that MyGet feed (made it private rather than public) and have switched to using the feed: `https://www.myget.org/F/fireeye/api/v2`. Perhaps you have an older version of the installer script? Currently I see all of our code using the latest MyGet feed (screenshot below). You should **not** have to enter any MyGet credentials. Also as a heads up, many packages are currently broken so they may not install correctly. We have upcoming changes planned for Q1 to help address this.

![Screen Shot 2021-12-27 at 16 46 14](https://user-images.githubusercontent.com/20993114/147509563-a3255e28-5a42-4474-883d-bf06c74d3efe.png)

**Comment by Evan-Sa** [comment]
@MalwareMechanic  Held off for few months on this issue until your team had time to address the broken packages issue. Please let me know if your team managed to the packages and will go ahead and try to run the script. Also former mandiant employee here so I hope you'll are doing well.

**Comment by vm-packages** [comment]
Thank you for your feedback! We've been working on major updates to FLARE VM over the last year.
The now revamped FLARE VM has just been released and will make the project more open and maintainable.
Please check out our blog post at https://www.mandiant.com/resources/blog/flarevm-open-to-public and give the new installation a try.

If this problem still persists with the new installation, please report:
- new tools or tool-related issues at https://github.com/mandiant/VM-Packages/issues
- ideas and issues related to the installer script and configuration at https://github.com/mandiant/flare-vm/issues

Please note that we use this message to close all legacy issues in this repository. We look forward to your feedback and support for the next generation of FLARE VM.
