### ISSUE TITLE
Install Failed, Fix below.

### ISSUE THREAD

**Issue by s3raph-x00** [mandiant/flare-vm#401]
Install failed, looks like one of the links for chocolatey has gone down.

https://boxstarter.org/bootstrapper.ps1 results in 404. 

The following works as an alternate link:

https://raw.githubusercontent.com/chocolatey/boxstarter/master/BuildScripts/bootstrapper.ps1

**Comment by facyber** [comment]
Hah, I just logged in to GitHub to open the very same issue. I was struggling for a bit as there was not a single error message that would indicate what is actually an issue.

**Comment by alkeldi** [comment]
This should be fixed by `boxstarter`, because the link `https://boxstarter.org/bootstrapper.ps1` has been the default for years. Not only `FLARE-VM` is affected, probably many other software is failing because of this problem. The issue is being tracked [here](https://github.com/chocolatey/boxstarter/issues/502)

The link provided above is a nice temporary fix to get the installation script of `FLARE-VM` to work, but it points to the master branch (which is in active development). A better fix should use the latest release (v2.13.0) to get `bootstrapper.ps1`

## A Better Alternate Link
https://raw.githubusercontent.com/chocolatey/boxstarter/v2.13.0/BuildScripts/bootstrapper.ps1

**Comment by mwallner** [comment]
Thanks for bringing this up.
I would recommend not using a static raw link to an old Boxstarter release, we'll fix the [corresponding issue](https://github.com/chocolatey/boxstarter/issues/502) on our site asap.
sorry for the inconvenience.

**Comment by mwallner** [comment]
Please note this issue has been resolved and should not occur anymore.

**Comment by alkeldi** [comment]
Thanks for the fix :)

**Comment by s3raph-x00** [comment]
Thanks, just verified good on my end.
