### ISSUE TITLE
Chocolatey call depth overflow

### ISSUE THREAD

**Issue by shikiko** [mandiant/flare-vm#458]
Having issues with  install.ps1

![image](https://github.com/mandiant/flare-vm/assets/14848134/ae9f7563-d7fc-4d1f-982f-28e301c6ebb1)

tried using $env:chocolateyVersion = '1.4.0' and Set-Alias -Name chocolatey -Value choco}.

Still receiving this error

**Comment by wan-ilhami** [comment]
yeah same goes to me anyone can help?

**Comment by Ana06** [comment]
This error happens when you use Choco 2 and `Set-Alias -Name chocolatey -Value choco` which you shouldn't do as our packages use more deprecated shims than `chocolatey` https://github.com/mandiant/VM-Packages/pull/429. Using `$env:chocolateyVersion = '1.4.0'` before running the installer should work until we update to Choco 2 and the just released Boxstarter 3.0.1
