### ISSUE TITLE
Configuration: File Explorer in the taskbar opens in the Tools folder

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-vm#535]
### Details

With https://github.com/mandiant/flare-vm/pull/531, we pin File Explorer in the taskbar. It would be nice if the pinned File Explorer would open in the Tools folder.

**Comment by emtuls** [comment]
After many trial and errors, I was unable to find a reliable way to make this work.

Windows 10 seems to completely neglect shortcuts that are not directly to applications and creating a shortcut to `File Explorer` with a `Start In:` set to the `Tools` Directory and attempting to pin this also proved unsuccessful.

One method that did manage to work only a single time (although this was not reproduceable), was to add a shortcut to the `Tools` directory into `C:\Users\user\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar`. 

Unfortunately, because this does not seem to be reproduceable, I ruled it out as an option.
