### ISSUE TITLE
Document -customLayout

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-vm#558]
### Details

We added the argument `-customLayout` for customizing taskbar pinning in https://github.com/mandiant/flare-vm/pull/531, but forgot to document it in the [`Installer Parameters` section](https://github.com/mandiant/flare-vm?tab=readme-ov-file#installer-parameters) and to add a `Custom Layout` section, similar to the [`Configuration`section](https://github.com/mandiant/flare-vm?tab=readme-ov-file#configuration).

@emtuls would you like to address this? 😄

**Comment by emtuls** [comment]
One thing to note, that I will add to the docs is that it looks like we can only pin things that are applications (.exe's) or shortcuts that point to applications from what it seems like through testing.

Depending on what needs to be done, some that can be considered is using a shortcut that points to `cmd.exe` (or possibly `powershell.exe`) with arguments set to do what might need to be done in order for the application to spawn. 
- If this route is considered, in order to mitigate an ugly `cmd/powershell` popup from appearing, we may need to modify the `VM-Install-Shortcut` function to include an extra argument of `WindowStyle` so that we can pass this into the `Chocolatey-InstallShortcut` function, which will let us spawn the window as `minimized/hidden`
- An example set of arguments that can be used with `cmd` would be like such: `C:\Windows\System32\cmd.exe /K "cd "C:\Tools\cyberchef" & start CyberChef_v10.5.2.html & exit"`
  - This example opens `cyberchef`, which is an `.html` file in the default `html` viewer.
