### ISSUE TITLE
Zimmerman Tools 404 Status

### ISSUE THREAD

**Issue by jsmithy2006** [mandiant/flare-vm#607]
### What's the problem?

Looks like Zimmerman Tools e.g. MFTECmd, bstrings, etc. are now hosted on a new server (https://download.mikestammer.com)

### Steps to Reproduce

1. .\install.ps1

### Environment

Virtualization software: VMWare
VM OS version: Windows 10 Pro

**Comment by heap-s** [comment]
This seems to throw a 404 as well? Individually you can use https://github.com/EricZimmerman/Get-ZimmermanTools/blob/master/Get-ZimmermanTools.ps1 I believe.

**Comment by heap-s** [comment]
@Ana06 https://github.com/mandiant/VM-Packages/pull/1123 This pull request solves this, but linter won't let pass due to Nuspec versioning. Is there a specific way version should be incremented?

**Comment by emtuls** [comment]
Thanks for catching that @jsmithy2006!

And thanks for the PR @heap-s! I noted a small change if you are able to make it: https://github.com/mandiant/VM-Packages/pull/1123#issuecomment-2311467652

Other than that, solid! If you need any help squashing, let me know and I can help make it work. :)

**Comment by emtuls** [comment]
Closed via https://github.com/mandiant/VM-Packages/pull/1123

**Comment by Ana06** [comment]
@jsmithy2006 thanks for reporting the issue. Our CI should have cached the issue, but after seeing this issue yesterday, I notice it has been broken for two weeks (trying to fix it in https://github.com/mandiant/VM-Packages/pull/1122 and https://github.com/mandiant/VM-Packages/pull/1124).

@jsmithy2006 notice that the issue was reported in the wrong repository as documented in our bug issue template:
> We track only bugs related to the installer in this repository. If the issue is related to a concrete tool or package (for example a single package that fails to install), please report it in [VM-Packages](https://github.com/mandiant/VM-Packages/issues/new?assignees=&labels=%3Abug%3A+bug&template=bug.yml)

This issue is not related to the installer but to the packages that install Zimmerman tools and should be reported and fixed in [VM-Packages](https://github.com/mandiant/VM-Packages). Just letting you now for future issues. :wink: 

Thanks for the fix @heap-s! The issue should be now fixed :wink:
